language: python

python:
  - "3.8.5"

install:
  - pip install -r requirements.txt

services:
  - mongodb

script:
  - py.test

addons:
  sauce_connect:
    username: "jasurbek1991"
    access_key: "baef3ba2041d4eb0b9ba6c60f775bfa4"
